### ISSUE TITLE
Call to CloudBees will hang forever if the service is down

### ISSUE THREAD

**Issue by leobeal-cpi** [rollout/rox-php#27]
According to [Guzzle docs](https://docs.guzzlephp.org/en/stable/request-options.html#timeout), the default timeout is 0, which will wait indefinitely for the response.
Since it seems no timeout is being set [here](https://github.com/rollout/rox-php/blob/1df28e29022e91951096b8da80cc6281926fabec/src/Rox/Core/Network/GuzzleHttpClient.php#L60), in case CloudBees call times out, the caller will hang forever instead of assuming the default value.

**Comment by leobeal-cpi** [comment]
Hi @AsafRollout We'd like to re-open this issue since we are still having issues related to timeouts in version 4.8.x due to retries in the Analytics API.
Could you guys cherry-pick this commit https://github.com/rollout/rox-php/commit/7fc9b0cc4c1c6faa95acef4097be3fb72000d7fb into 4.8.x and create a new tag?

Thanks a lot!

**Comment by AsafRollout** [comment]
sure, i'll add it to 4.8 too 👍 
hopefully it will be released on Monday

**Comment by AsafRollout** [comment]
released 4.8.2

**Comment by leobeal-cpi** [comment]
Thanks a lot @AsafRollout
