### ISSUE TITLE
[Bug] Cannot get a string value that represents an encoded JSON object

### ISSUE THREAD

**Issue by tcarrio** [rollout/rox-php#37]
I have validated this will multiple payloads, and the only one that **won't** fail is an empty object.

|Input|Success|
|-----|-------|
|`{}` |Yes|
|`{"a":"b"}`|No|
|`{"name":"tcarrio"}`|No|

The entirety of the string has the quotations escaped, and the local Roxy server returns the values as you would expect to see them for it to be resolved correctly as a string value.

Example response JSON from the `/flags` endpoint (showing only the flag in question):

```json
{
    "flagName": "dev.openfeature.object_flag",
    "expression": "\"{\"name\":\"OpenFeature\",\"version\":\"1.0.0\"}\"",
    "lastModifiedDate": "2022-11-17T00:50:01.549Z"
}
```

This likely has something to do with the string processing post response. With the empty object example I do resolve the value and can `json_decode` into an array.

**Comment by CristianCurteanu** [comment]
Seems like so, at least using the string with double quotes. However, it worked when I defined the object string using single quotes, like this:

```
'"{\"name\":\"OpenFeature\",\"version\":\"1.0.0\"}"'
```

Test code:
```php
class Container
{
    public $expressionFlag;

    public function __construct()
    {
        $this->expressionFlag = new RoxString('"{\"name\":\"OpenFeature\",\"version\":\"1.0.0\"}"');
    }
}

// ... All the $container instance setup

echo ">>> expressionFlag is " . $container->expressionFlag->getValue() . "\n"; // 

$decoded = json_decode($container->expressionFlag->getValue(), true);
echo ">>> decoded: " . $decoded;
```

Result logs:
```
>>> expressionFlag is "{\"name\":\"OpenFeature\",\"version\":\"1.0.0\"}"
>>> decoded: {"name":"OpenFeature","version":"1.0.0"}
```

In case I was using double quotes, the `$decoded` object was empty.

**Comment by CristianCurteanu** [comment]
Closing this issue as the solution is one describe in the message above. In case solution will not work for some reason, we can re-open (or create another one) with updated issue details.
