### ISSUE TITLE
Breaking change in 5.0.3

### ISSUE THREAD

**Issue by dbhynds** [rollout/rox-php#47]
Between versions 5.0.2 and 5.0.3, this library updated the dependency for `kevinrob/guzzle-cache-middleware` from `^3.2` to `^4.0`. See: https://github.com/rollout/rox-php/compare/5.0.2...5.0.3#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R37

The upgrade to v4 contains backwards-incompatible changes that require the cache to be cleared at the time of deployment as described here: https://github.com/Kevinrob/guzzle-cache-middleware/issues/172. As mentioned in the comments, "it's especially... dangerous, because more often it may affect production than test or dev environments."

Use caution when upgrading to version v5.0.3, as you must clear the cache after implementing these changes.

**Comment by CristianCurteanu** [comment]
@dbhynds If I understand correctly, this issue was added in order to prevent incompatibility issues due to `kevinrob/guzzle-cache-middleware` upgrade, and cleanup the cache, as it could raise runtime errors, is that correct?

**Comment by CristianCurteanu** [comment]
Due to warning message added to [Readme](https://github.com/rollout/rox-php/pull/51), this ticket can be closed

**Comment by CristianCurteanu** [comment]
Warning message added to the Readme file, I believe we can close this issue
